# Generated by Django 3.2.12 on 2022-04-08 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_recommend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_db_url',
            field=models.CharField(default='none', max_length=128),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_imdb_id',
            field=models.CharField(default='none', max_length=32),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_update_time',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
