# Generated by Django 3.2.12 on 2022-04-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_recommend', '0002_auto_20220408_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_score_sum',
            field=models.CharField(default='', max_length=64),
        ),
    ]
