# Generated by Django 3.2.12 on 2022-04-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_recommend', '0003_movie_movie_score_sum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(default='', max_length=128)),
                ('movie_imdb_id', models.CharField(default='none', max_length=32)),
                ('movie_poster', models.CharField(default='', max_length=128)),
            ],
        ),
    ]
