# Generated by Django 3.2.12 on 2022-04-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_recommend', '0004_movie_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_index',
            name='movie_poster',
            field=models.CharField(default='', max_length=255),
        ),
    ]
