# Generated by Django 3.2.12 on 2022-04-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_recommend', '0005_alter_movie_index_movie_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_index',
            name='movie_title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
