# Generated by Django 3.2.12 on 2022-04-12 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_recommend', '0006_alter_movie_index_movie_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie_index',
            new_name='MovieIndex',
        ),
    ]
