# Generated by Django 3.2.12 on 2022-04-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_recommend', '0007_rename_movie_index_movieindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_imdb_id', models.CharField(default='none', max_length=32)),
                ('user_id', models.CharField(default='none', max_length=32)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('comments', models.TextField(default='')),
                ('time_stamp', models.CharField(default='1648699200', max_length=32)),
            ],
        ),
    ]
