# Generated by Django 3.2.12 on 2022-04-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_recommend', '0008_movierating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movierating',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
