# Generated by Django 3.2.12 on 2022-04-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_recommend', '0010_movierating_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_other_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
