# Generated by Django 3.2.12 on 2022-04-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_recommend', '0012_movielens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_poster',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='movielens',
            name='movie_poster',
            field=models.CharField(default='', max_length=255),
        ),
    ]
