# Generated by Django 3.2.12 on 2022-04-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_recommend', '0015_auto_20220415_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_actors',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_country',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_desc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_director',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_length',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_other_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_poster',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_score',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_score_sum',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_time',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_title',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_type',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
