# Generated by Django 3.2.12 on 2022-04-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_recommend', '0016_auto_20220417_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_other_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='movielens',
            name='movie_other_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
