# Generated by Django 3.2.12 on 2022-03-25 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.CharField(default='static/user_avatar.jpg', max_length=128, verbose_name='用户头像'),
        ),
    ]
